sudo: false
language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby
matrix:
  fast_finish: true
before_install:
  - gem install bundler
script: bundle exec rake -t
