name: CI

on:
  push: {}
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.owner.login != 'lgierth'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - '2.1.9' # earliest supported by ruby/setup-ruby
          - '2.6.0' # test Promise.map_value ruby version condition
          - '2.7.2' # latest passing on CI, will update to 3.0.0 in a follow-up PR
          - 'jruby'

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake
